use super::region::KEYPHRASE_REGION_MAP;
use crate::{prelude::*, service::var_service::get_docker_volume};
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};
use std::{
    process::Command,
    str::from_utf8,
    sync::{Arc, Mutex},
};
use unidecode::unidecode;
pub(super) async fn get_regions(text: &[&str]) -> Result<Vec<String>> {
    let text = text
        .join(" ")
        .replace('\'', r"\'")
        .replace("&#39;", r"\'")
        .replace("&amp;", "&")
        .replace(['"', '`', '‘', '’', '–'], "")
        .replace("'s ", " ")
        .replace("s' ", " ");
    let identified_regions = get_flashgeotext_regions(&text).await?;

    let text = unidecode(&text.replace(r"\'", "'").to_lowercase());
    let identified_regions = Arc::new(Mutex::new(identified_regions));
    KEYPHRASE_REGION_MAP
        .par_iter()
        .for_each(|(keyphrases, region)| {
            let identified_regions = Arc::clone(&identified_regions);
            let mut identified_regions_locked = match identified_regions.lock() {
                Ok(regions) => regions,
                Err(poisoned) => {
                    tracing::error!("Poisoned lock: {:?}", poisoned);
                    return;
                }
            };

            if identified_regions_locked.contains(region) {
                return;
            }

            for keyphrase in keyphrases.iter() {
                if text.contains(keyphrase) {
                    identified_regions_locked.push(region);
                    break;
                }
            }
        });

    let mut regions = match identified_regions.lock() {
        Ok(regions) => regions.clone(),
        Err(poisoned) => {
            tracing::error!("Poisoned lock: {:?}", poisoned);
            Vec::new()
        }
    };

    if text.contains("georgia") && !regions.contains(&"us") && !regions.contains(&"ge") {
        regions.push("ge");
    }
    if text.contains("ireland") && !text.contains("northern ireland") && !regions.contains(&"ie") {
        regions.push("ie");
    }
    if text.contains("mexico") && !text.contains("new mexico") && !regions.contains(&"mx") {
        regions.push("mx");
    }
    if text.contains("trump") && !regions.is_empty() {
        regions.push("us");
    }

    Ok(regions.iter().map(|s| s.to_string()).collect())
}

async fn get_flashgeotext_regions(text: &String) -> Result<Vec<&'static str>> {
    let docker_volume = get_docker_volume().await?;
    let regions = Command::new(format!("{}/p3venv/bin/python", docker_volume))
    .arg("-c")
    .arg(format!(
        "import sys; sys.path.append('{}'); from media_to_regions import get_regions; print(get_regions('{}'))",
        docker_volume, text
    ))
    .output()?;

    let output = from_utf8(&regions.stdout)?;
    if output.is_empty() {
        tracing::error!("Flashgeotext error from body: {}", text);
        return Ok(Vec::new());
    }

    if output == "[]\n" {
        return Ok(Vec::new());
    }

    let output: Vec<&'static str> = output
        .trim()
        .replace(['[', ']', '\''], "")
        .split(", ")
        .map(|s| &*Box::leak(s.to_string().into_boxed_str()))
        .collect();
    let regions = output
        .into_iter()
        .filter(|s| {
            !matches!(
                *s,
                "Chad" | "Georgia" | "Guinea-Bissau" | "Jordan" | "Republic of Congo"
            )
        })
        .filter_map(|s| get_iso_from_name(s))
        .collect();

    Ok(regions)
}

pub fn get_iso_from_name(name: &str) -> Option<&str> {
    match name {
        "Andorra" => Some("ad"),
        "United Arab Emirates" => Some("ae"),
        "Afghanistan" => Some("af"),
        "Antigua and Barbuda" => Some("ag"),
        "Anguilla" => Some("ai"),
        "Albania" => Some("al"),
        "Armenia" => Some("am"),
        "Angola" => Some("ao"),
        "Antarctica" => Some("aq"),
        "Argentina" => Some("ar"),
        "American Samoa" => Some("as"),
        "Austria" => Some("at"),
        "Australia" => Some("au"),
        "Aruba" => Some("aw"),
        "Aland Islands" => Some("ax"),
        "Azerbaijan" => Some("az"),
        "Bosnia and Herzegovina" => Some("ba"),
        "Barbados" => Some("bb"),
        "Bangladesh" => Some("bd"),
        "Belgium" => Some("be"),
        "Burkina Faso" => Some("bf"),
        "Bulgaria" => Some("bg"),
        "Bahrain" => Some("bh"),
        "Burundi" => Some("bi"),
        "Benin" => Some("bj"),
        "Saint Barthelemy" => Some("bl"),
        "Bermuda" => Some("bm"),
        "Brunei" => Some("bn"),
        "Bolivia" => Some("bo"),
        "Bonaire, Sint Eustatius, and Saba" => Some("bq"),
        "Brazil" => Some("br"),
        "Bahamas" => Some("bs"),
        "Bhutan" => Some("bt"),
        "Bouvet Island" => Some("bv"),
        "Botswana" => Some("bw"),
        "Belarus" => Some("by"),
        "Belize" => Some("bz"),
        "Canada" => Some("ca"),
        "Cocos (Keeling) Islands" => Some("cc"),
        "Democratic Republic of the Congo" => Some("cd"),
        "Central African Republic" => Some("cf"),
        "Republic of the Congo" => Some("cg"),
        "Switzerland" => Some("ch"),
        "Ivory Coast" => Some("ci"),
        "Cook Islands" => Some("ck"),
        "Chile" => Some("cl"),
        "Cameroon" => Some("cm"),
        "China" => Some("cn"),
        "Colombia" => Some("co"),
        "Costa Rica" => Some("cr"),
        "Cuba" => Some("cu"),
        "Cape Verde" => Some("cv"),
        "Curacao" => Some("cw"),
        "Christmas Island" => Some("cx"),
        "Cyprus" => Some("cy"),
        "Czech Republic" => Some("cz"),
        "Germany" => Some("de"),
        "Djibouti" => Some("dj"),
        "Denmark" => Some("dk"),
        "Dominica" => Some("dm"),
        "Dominican Republic" => Some("do"),
        "Algeria" => Some("dz"),
        "Ecuador" => Some("ec"),
        "Estonia" => Some("ee"),
        "Egypt" => Some("eg"),
        "Western Sahara" => Some("eh"),
        "Eritrea" => Some("er"),
        "Spain" => Some("es"),
        "Ethiopia" => Some("et"),
        "Finland" => Some("fi"),
        "Fiji" => Some("fj"),
        "Falkland Islands" => Some("fk"),
        "Micronesia" => Some("fm"),
        "Faroe Islands" => Some("fo"),
        "France" => Some("fr"),
        "Gabon" => Some("ga"),
        "United Kingdom" => Some("gb"),
        "Grenada" => Some("gd"),
        "Georgia" => Some("ge"),
        "French Guiana" => Some("gf"),
        "Guernsey" => Some("gg"),
        "Ghana" => Some("gh"),
        "Gibraltar" => Some("gi"),
        "Greenland" => Some("gl"),
        "Gambia" => Some("gm"),
        "Guinea" => Some("gn"),
        "Guadeloupe" => Some("gp"),
        "Equatorial Guinea" => Some("gq"),
        "Greece" => Some("gr"),
        "South Georgia and the South Sandwich Islands" => Some("gs"),
        "Guatemala" => Some("gt"),
        "Guam" => Some("gu"),
        "Guinea-Bissau" => Some("gw"),
        "Guyana" => Some("gy"),
        "Hong Kong" => Some("hk"),
        "Heard Island and McDonald Islands" => Some("hm"),
        "Honduras" => Some("hn"),
        "Croatia" => Some("hr"),
        "Haiti" => Some("ht"),
        "Hungary" => Some("hu"),
        "Indonesia" => Some("id"),
        "Ireland" => Some("ie"),
        "Israel" => Some("il"),
        "Isle of Man" => Some("im"),
        "India" => Some("in"),
        "British Indian Ocean Territory" => Some("io"),
        "Iraq" => Some("iq"),
        "Iran" => Some("ir"),
        "Iceland" => Some("is"),
        "Italy" => Some("it"),
        "Jersey" => Some("je"),
        "Jamaica" => Some("jm"),
        "Jordan" => Some("jo"),
        "Japan" => Some("jp"),
        "Kenya" => Some("ke"),
        "Kyrgyzstan" => Some("kg"),
        "Cambodia" => Some("kh"),
        "Kiribati" => Some("ki"),
        "Comoros" => Some("km"),
        "Saint Kitts and Nevis" => Some("kn"),
        "North Korea" => Some("kp"),
        "South Korea" => Some("kr"),
        "Kuwait" => Some("kw"),
        "Cayman Islands" => Some("ky"),
        "Kazakhstan" => Some("kz"),
        "Laos" => Some("la"),
        "Lebanon" => Some("lb"),
        "Saint Lucia" => Some("lc"),
        "Liechtenstein" => Some("li"),
        "Sri Lanka" => Some("lk"),
        "Liberia" => Some("lr"),
        "Lesotho" => Some("ls"),
        "Lithuania" => Some("lt"),
        "Luxembourg" => Some("lu"),
        "Latvia" => Some("lv"),
        "Libya" => Some("ly"),
        "Morocco" => Some("ma"),
        "Monaco" => Some("mc"),
        "Moldova" => Some("md"),
        "Montenegro" => Some("me"),
        "Saint Martin" => Some("mf"),
        "Madagascar" => Some("mg"),
        "Marshall Islands" => Some("mh"),
        "North Macedonia" => Some("mk"),
        "Mali" => Some("ml"),
        "Myanmar" => Some("mm"),
        "Mongolia" => Some("mn"),
        "Macau" => Some("mo"),
        "Northern Mariana Islands" => Some("mp"),
        "Martinique" => Some("mq"),
        "Mauritania" => Some("mr"),
        "Montserrat" => Some("ms"),
        "Malta" => Some("mt"),
        "Mauritius" => Some("mu"),
        "Maldives" => Some("mv"),
        "Malawi" => Some("mw"),
        "Mexico" => Some("mx"),
        "Malaysia" => Some("my"),
        "Mozambique" => Some("mz"),
        "Namibia" => Some("na"),
        "New Caledonia" => Some("nc"),
        "Niger" => Some("ne"),
        "Norfolk Island" => Some("nf"),
        "Nigeria" => Some("ng"),
        "Nicaragua" => Some("ni"),
        "Netherlands" => Some("nl"),
        "Norway" => Some("no"),
        "Nepal" => Some("np"),
        "Nauru" => Some("nr"),
        "Niue" => Some("nu"),
        "New Zealand" => Some("nz"),
        "Oman" => Some("om"),
        "Panama" => Some("pa"),
        "Peru" => Some("pe"),
        "French Polynesia" => Some("pf"),
        "Papua New Guinea" => Some("pg"),
        "Philippines" => Some("ph"),
        "Pakistan" => Some("pk"),
        "Poland" => Some("pl"),
        "Saint Pierre and Miquelon" => Some("pm"),
        "Pitcairn Islands" => Some("pn"),
        "Puerto Rico" => Some("pr"),
        "Palestine" => Some("ps"),
        "Portugal" => Some("pt"),
        "Palau" => Some("pw"),
        "Paraguay" => Some("py"),
        "Qatar" => Some("qa"),
        "Reunion" => Some("re"),
        "Romania" => Some("ro"),
        "Serbia" => Some("rs"),
        "Russia" => Some("ru"),
        "Rwanda" => Some("rw"),
        "Saudi Arabia" => Some("sa"),
        "Solomon Islands" => Some("sb"),
        "Seychelles" => Some("sc"),
        "Sudan" => Some("sd"),
        "Sweden" => Some("se"),
        "Singapore" => Some("sg"),
        "Saint Helena" => Some("sh"),
        "Slovenia" => Some("si"),
        "Svalbard and Jan Mayen" => Some("sj"),
        "Slovakia" => Some("sk"),
        "Sierra Leone" => Some("sl"),
        "San Marino" => Some("sm"),
        "Senegal" => Some("sn"),
        "Somalia" => Some("so"),
        "Suriname" => Some("sr"),
        "South Sudan" => Some("ss"),
        "Sao Tome and Principe" => Some("st"),
        "El Salvador" => Some("sv"),
        "Sint Maarten" => Some("sx"),
        "Syria" => Some("sy"),
        "Eswatini" => Some("sz"),
        "Turks and Caicos Islands" => Some("tc"),
        "Chad" => Some("td"),
        "French Southern Territories" => Some("tf"),
        "Togo" => Some("tg"),
        "Thailand" => Some("th"),
        "Tajikistan" => Some("tj"),
        "Tokelau" => Some("tk"),
        "East Timor" => Some("tl"),
        "Turkmenistan" => Some("tm"),
        "Tunisia" => Some("tn"),
        "Tonga" => Some("to"),
        "Turkey" => Some("tr"),
        "Trinidad and Tobago" => Some("tt"),
        "Tuvalu" => Some("tv"),
        "Taiwan" => Some("tw"),
        "Tanzania" => Some("tz"),
        "Ukraine" => Some("ua"),
        "Uganda" => Some("ug"),
        "United States Minor Outlying Islands" => Some("um"),
        "United States" => Some("us"),
        "Uruguay" => Some("uy"),
        "Uzbekistan" => Some("uz"),
        "Vatican City" => Some("va"),
        "Saint Vincent and the Grenadines" => Some("vc"),
        "Venezuela" => Some("ve"),
        "British Virgin Islands" => Some("vg"),
        "United States Virgin Islands" => Some("vi"),
        "Vietnam" => Some("vn"),
        "Vanuatu" => Some("vu"),
        "Wallis and Futuna" => Some("wf"),
        "Samoa" => Some("ws"),
        "Yemen" => Some("ye"),
        "Mayotte" => Some("yt"),
        "Kosovo" => Some("xk"),
        "South Africa" => Some("za"),
        "Zambia" => Some("zm"),
        "Zimbabwe" => Some("zw"),
        _ => None,
    }
}

// pub fn get_name_from_iso(iso_code: &str) -> Option<&str> {
//     match iso_code {
//         "AD" => Some("Andorra"),
//         "AE" => Some("United Arab Emirates"),
//         "AF" => Some("Afghanistan"),
//         "AG" => Some("Antigua and Barbuda"),
//         "AI" => Some("Anguilla"),
//         "AL" => Some("Albania"),
//         "AM" => Some("Armenia"),
//         "AO" => Some("Angola"),
//         "AQ" => Some("Antarctica"),
//         "AR" => Some("Argentina"),
//         "AS" => Some("American Samoa"),
//         "AT" => Some("Austria"),
//         "AU" => Some("Australia"),
//         "AW" => Some("Aruba"),
//         "AX" => Some("Aland Islands"),
//         "AZ" => Some("Azerbaijan"),
//         "BA" => Some("Bosnia and Herzegovina"),
//         "BB" => Some("Barbados"),
//         "BD" => Some("Bangladesh"),
//         "BE" => Some("Belgium"),
//         "BF" => Some("Burkina Faso"),
//         "BG" => Some("Bulgaria"),
//         "BH" => Some("Bahrain"),
//         "BI" => Some("Burundi"),
//         "BJ" => Some("Benin"),
//         "BL" => Some("Saint Barthelemy"),
//         "BM" => Some("Bermuda"),
//         "BN" => Some("Brunei"),
//         "BO" => Some("Bolivia"),
//         "BQ" => Some("Bonaire, Sint Eustatius, and Saba"),
//         "BR" => Some("Brazil"),
//         "BS" => Some("Bahamas"),
//         "BT" => Some("Bhutan"),
//         "BV" => Some("Bouvet Island"),
//         "BW" => Some("Botswana"),
//         "BY" => Some("Belarus"),
//         "BZ" => Some("Belize"),
//         "CA" => Some("Canada"),
//         "CC" => Some("Cocos (Keeling) Islands"),
//         "CD" => Some("Democratic Republic of the Congo"),
//         "CF" => Some("Central African Republic"),
//         "CG" => Some("Republic of the Congo"),
//         "CH" => Some("Switzerland"),
//         "CI" => Some("Ivory Coast"),
//         "CK" => Some("Cook Islands"),
//         "CL" => Some("Chile"),
//         "CM" => Some("Cameroon"),
//         "CN" => Some("China"),
//         "CO" => Some("Colombia"),
//         "CR" => Some("Costa Rica"),
//         "CU" => Some("Cuba"),
//         "CV" => Some("Cape Verde"),
//         "CW" => Some("Curacao"),
//         "CX" => Some("Christmas Island"),
//         "CY" => Some("Cyprus"),
//         "CZ" => Some("Czech Republic"),
//         "DE" => Some("Germany"),
//         "DJ" => Some("Djibouti"),
//         "DK" => Some("Denmark"),
//         "DM" => Some("Dominica"),
//         "DO" => Some("Dominican Republic"),
//         "DZ" => Some("Algeria"),
//         "EC" => Some("Ecuador"),
//         "EE" => Some("Estonia"),
//         "EG" => Some("Egypt"),
//         "EH" => Some("Western Sahara"),
//         "ER" => Some("Eritrea"),
//         "ES" => Some("Spain"),
//         "ET" => Some("Ethiopia"),
//         "FI" => Some("Finland"),
//         "FJ" => Some("Fiji"),
//         "FK" => Some("Falkland Islands"),
//         "FM" => Some("Micronesia"),
//         "FO" => Some("Faroe Islands"),
//         "FR" => Some("France"),
//         "GA" => Some("Gabon"),
//         "GB" => Some("United Kingdom"),
//         "GD" => Some("Grenada"),
//         "GE" => Some("Georgia"),
//         "GF" => Some("French Guiana"),
//         "GG" => Some("Guernsey"),
//         "GH" => Some("Ghana"),
//         "GI" => Some("Gibraltar"),
//         "GL" => Some("Greenland"),
//         "GM" => Some("Gambia"),
//         "GN" => Some("Guinea"),
//         "GP" => Some("Guadeloupe"),
//         "GQ" => Some("Equatorial Guinea"),
//         "GR" => Some("Greece"),
//         "GS" => Some("South Georgia and the South Sandwich Islands"),
//         "GT" => Some("Guatemala"),
//         "GU" => Some("Guam"),
//         "GW" => Some("Guinea-Bissau"),
//         "GY" => Some("Guyana"),
//         "HK" => Some("Hong Kong"),
//         "HM" => Some("Heard Island and McDonald Islands"),
//         "HN" => Some("Honduras"),
//         "HR" => Some("Croatia"),
//         "HT" => Some("Haiti"),
//         "HU" => Some("Hungary"),
//         "ID" => Some("Indonesia"),
//         "IE" => Some("Ireland"),
//         "IL" => Some("Israel"),
//         "IM" => Some("Isle of Man"),
//         "IN" => Some("India"),
//         "IO" => Some("British Indian Ocean Territory"),
//         "IQ" => Some("Iraq"),
//         "IR" => Some("Iran"),
//         "IS" => Some("Iceland"),
//         "IT" => Some("Italy"),
//         "JE" => Some("Jersey"),
//         "JM" => Some("Jamaica"),
//         "JO" => Some("Jordan"),
//         "JP" => Some("Japan"),
//         "KE" => Some("Kenya"),
//         "KG" => Some("Kyrgyzstan"),
//         "KH" => Some("Cambodia"),
//         "KI" => Some("Kiribati"),
//         "KM" => Some("Comoros"),
//         "KN" => Some("Saint Kitts and Nevis"),
//         "KP" => Some("North Korea"),
//         "KR" => Some("South Korea"),
//         "KW" => Some("Kuwait"),
//         "KY" => Some("Cayman Islands"),
//         "KZ" => Some("Kazakhstan"),
//         "LA" => Some("Laos"),
//         "LB" => Some("Lebanon"),
//         "LC" => Some("Saint Lucia"),
//         "LI" => Some("Liechtenstein"),
//         "LK" => Some("Sri Lanka"),
//         "LR" => Some("Liberia"),
//         "LS" => Some("Lesotho"),
//         "LT" => Some("Lithuania"),
//         "LU" => Some("Luxembourg"),
//         "LV" => Some("Latvia"),
//         "LY" => Some("Libya"),
//         "MA" => Some("Morocco"),
//         "MC" => Some("Monaco"),
//         "MD" => Some("Moldova"),
//         "ME" => Some("Montenegro"),
//         "MF" => Some("Saint Martin"),
//         "MG" => Some("Madagascar"),
//         "MH" => Some("Marshall Islands"),
//         "MK" => Some("North Macedonia"),
//         "ML" => Some("Mali"),
//         "MM" => Some("Myanmar"),
//         "MN" => Some("Mongolia"),
//         "MO" => Some("Macau"),
//         "MP" => Some("Northern Mariana Islands"),
//         "MQ" => Some("Martinique"),
//         "MR" => Some("Mauritania"),
//         "MS" => Some("Montserrat"),
//         "MT" => Some("Malta"),
//         "MU" => Some("Mauritius"),
//         "MV" => Some("Maldives"),
//         "MW" => Some("Malawi"),
//         "MX" => Some("Mexico"),
//         "MY" => Some("Malaysia"),
//         "MZ" => Some("Mozambique"),
//         "NA" => Some("Namibia"),
//         "NC" => Some("New Caledonia"),
//         "NE" => Some("Niger"),
//         "NF" => Some("Norfolk Island"),
//         "NG" => Some("Nigeria"),
//         "NI" => Some("Nicaragua"),
//         "NL" => Some("Netherlands"),
//         "NO" => Some("Norway"),
//         "NP" => Some("Nepal"),
//         "NR" => Some("Nauru"),
//         "NU" => Some("Niue"),
//         "NZ" => Some("New Zealand"),
//         "OM" => Some("Oman"),
//         "PA" => Some("Panama"),
//         "PE" => Some("Peru"),
//         "PF" => Some("French Polynesia"),
//         "PG" => Some("Papua New Guinea"),
//         "PH" => Some("Philippines"),
//         "PK" => Some("Pakistan"),
//         "PL" => Some("Poland"),
//         "PM" => Some("Saint Pierre and Miquelon"),
//         "PN" => Some("Pitcairn Islands"),
//         "PR" => Some("Puerto Rico"),
//         "PS" => Some("Palestine"),
//         "PT" => Some("Portugal"),
//         "PW" => Some("Palau"),
//         "PY" => Some("Paraguay"),
//         "QA" => Some("Qatar"),
//         "RE" => Some("Reunion"),
//         "RO" => Some("Romania"),
//         "RS" => Some("Serbia"),
//         "RU" => Some("Russia"),
//         "RW" => Some("Rwanda"),
//         "SA" => Some("Saudi Arabia"),
//         "SB" => Some("Solomon Islands"),
//         "SC" => Some("Seychelles"),
//         "SD" => Some("Sudan"),
//         "SE" => Some("Sweden"),
//         "SG" => Some("Singapore"),
//         "SH" => Some("Saint Helena"),
//         "SI" => Some("Slovenia"),
//         "SJ" => Some("Svalbard and Jan Mayen"),
//         "SK" => Some("Slovakia"),
//         "SL" => Some("Sierra Leone"),
//         "SM" => Some("San Marino"),
//         "SN" => Some("Senegal"),
//         "SO" => Some("Somalia"),
//         "SR" => Some("Suriname"),
//         "SS" => Some("South Sudan"),
//         "ST" => Some("Sao Tome and Principe"),
//         "SV" => Some("El Salvador"),
//         "SX" => Some("Sint Maarten"),
//         "SY" => Some("Syria"),
//         "SZ" => Some("Eswatini"),
//         "TC" => Some("Turks and Caicos Islands"),
//         "TD" => Some("Chad"),
//         "TF" => Some("French Southern Territories"),
//         "TG" => Some("Togo"),
//         "TH" => Some("Thailand"),
//         "TJ" => Some("Tajikistan"),
//         "TK" => Some("Tokelau"),
//         "TL" => Some("East Timor"),
//         "TM" => Some("Turkmenistan"),
//         "TN" => Some("Tunisia"),
//         "TO" => Some("Tonga"),
//         "TR" => Some("Turkey"),
//         "TT" => Some("Trinidad and Tobago"),
//         "TV" => Some("Tuvalu"),
//         "TW" => Some("Taiwan"),
//         "TZ" => Some("Tanzania"),
//         "UA" => Some("Ukraine"),
//         "UG" => Some("Uganda"),
//         "UM" => Some("United States Minor Outlying Islands"),
//         "US" => Some("United States"),
//         "UY" => Some("Uruguay"),
//         "UZ" => Some("Uzbekistan"),
//         "VA" => Some("Vatican City"),
//         "VC" => Some("Saint Vincent and the Grenadines"),
//         "VE" => Some("Venezuela"),
//         "VG" => Some("British Virgin Islands"),
//         "VI" => Some("United States Virgin Islands"),
//         "VN" => Some("Vietnam"),
//         "VU" => Some("Vanuatu"),
//         "WF" => Some("Wallis and Futuna"),
//         "WS" => Some("Samoa"),
//         "YE" => Some("Yemen"),
//         "YT" => Some("Mayotte"),
//         "XK" => Some("Kosovo"),
//         "ZA" => Some("South Africa"),
//         "ZM" => Some("Zambia"),
//         "ZW" => Some("Zimbabwe"),
//         _ => None,
//     }
// }
